download_sleep_interval:
  min: 3
  max: 6

max_downloads_per_run: 50

sites:
  - &YouTube 0

s3_archive: false
s3_bucket: ""
delete_old_info: true
delete_old_thumbnail: true

# Filename template given to scripts
filename_template: "path/%s"

scripts:
  - &test_script
    name: "Test"
    required_fields:
      # New videos have the filename field set to None
      - new
      - deleted
      - new_deleted
    script: echo 1

after:
  - *test_script

playlists:
  - name: "test"
    playlist_id: "id"
    site: *YouTube
    archive: true # false by default
    after:
      - *test_script
